-- Create Rounds table
create table public.rounds (
  id bigint generated by default as identity primary key,
  name text not null,
  participants text not null,
  dates text not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.rounds enable row level security;

-- Allow read access to everyone
create policy "Enable read access for all users"
on public.rounds for select
using (true);

-- Allow insert/update/delete access only to authenticated users (admins)
create policy "Enable insert for authenticated users only"
on public.rounds for insert
with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
on public.rounds for update
using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
on public.rounds for delete
using (auth.role() = 'authenticated');
