-- Create Round Images table
create table public.round_images (
  id bigint generated by default as identity primary key,
  round_id bigint references public.rounds(id) on delete cascade not null,
  image_url text not null,
  name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.round_images enable row level security;

-- Allow read access to everyone
create policy "Enable read access for all users"
on public.round_images for select
using (true);

-- Allow insert/update/delete access only to authenticated users (admins)
create policy "Enable insert for authenticated users only"
on public.round_images for insert
with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
on public.round_images for update
using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
on public.round_images for delete
using (auth.role() = 'authenticated');
